package pojo;
// Generated 01-Oct-2018 22:10:55 by Hibernate Tools 4.3.1

import dao.AdminDAO;
import dao.CategoryDAO;
import java.io.File;
import java.io.FileOutputStream;
import java.io.InputStream;
import java.util.List;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.servlet.http.Part;
import javax.persistence.Transient;




/**
 * Category generated by hbm2java
 */
@ManagedBean
@SessionScoped

public class Category  implements java.io.Serializable {
    
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
     private Integer idCategory;
     private String category;
     private String picture;
     private List<Category> Category;  
     private List<TblLyric> listLyric;
     private int selectedCategory;
     private String msg;
     
     @Transient
     private Part imgpath;
     
     @Transient
     private boolean uploaded;

    public Part getImgpath() {
        return imgpath;
    }

    public void setImgpath(Part imgpath) {
        this.imgpath = imgpath;
    }
     
    public Category() {
    }

    public Category(String category, String picture) {
       this.category = category;
       this.picture = picture;
    }
   
    public Integer getIdCategory() {
        return this.idCategory;
    }
    
    public void setIdCategory(Integer idCategory) {
        this.idCategory = idCategory;
    }
    public String getCategory() {
        return this.category;
    }
    
    public void setCategory(String category) {
        this.category = category;
    }
    public String getPicture() {
        return this.picture;
    }
    
    public void setPicture(String picture) {
        this.picture = picture;
    }
    
    public boolean isUploaded() {
        return uploaded;
    }
    
    public void setUploaded(boolean uploaded) {
        this.uploaded = uploaded;
    }
    
     public List<Category> getListCategory() {
        return Category;
    }

    public void setListCategory(List<Category> listCategory) {
        this.Category = listCategory;
    }

    public int getSelectedCategory() {
        return selectedCategory;
    }

    public void setselectedCategory(int selectedCategory) {
        
        this.selectedCategory = selectedCategory;
    }

    public String getMsg() {
        return msg;
    }

    public void setMsg(String msg) {
        this.msg = msg;
    }

    public List<TblLyric> getListLyric() {
        return listLyric;
    }

    public void setListLyric(List<TblLyric> listLyric) {
        this.listLyric = listLyric;
    }


    public void saveData() {
       
        setPicture(doUpload());
        
        CategoryDAO tblCategory = new CategoryDAO();
        tblCategory.addCategory(this);
        
        this.msg = "Berhasil simpan data..";
        this.clearAll();
    }

    public void updateData() {
        CategoryDAO tblCategory = new CategoryDAO();
        tblCategory.updateCategory(this);
        this.msg = "Berhasil update data..";
        this.clearAll();
    }

    public void deleteData() {
        CategoryDAO Category = new CategoryDAO();
        Category.destroyCategory(this);
        this.msg = "Berhasil hapus data..";
        this.clearAll();
    }

    public List<Category> getAllRecords() {
        this.msg = null;
         CategoryDAO tblCategory = new CategoryDAO();
        Category = tblCategory.retrieveCategory();
        return Category;
    }

    public List<Category> ambilAllCategoryID() {
        CategoryDAO tblCategory = new CategoryDAO();
        Category = tblCategory.retrieveCategoryID();
        return Category;
    }

    public void infoCategoryByID() {
        CategoryDAO tblCategory = new CategoryDAO();
        List<Category> ls = tblCategory.getbyID(selectedCategory);
        this.idCategory = ls.get(0).idCategory;
        this.category = ls.get(0).category;
        this.picture = ls.get(0).picture;
       
    }

    public String doUpload() {
                String path = null;
                String pathValue = null;
                try {
                        InputStream in = imgpath.getInputStream();
                        File f = new File ("E:\\Documents\\NetBeansProjects\\PargibsLyric\\web\\images\\"+imgpath.getSubmittedFileName());
                        f.createNewFile();
                        FileOutputStream out = new FileOutputStream(f);
                        
                        byte[] buffer = new byte[1024];
                        int length;
                        while ((length=in.read(buffer))>0) {
                            out.write(buffer, 0, length);
                        }
                        out.close();
                        in.close();
                        
                        path = String.valueOf(f.getAbsolutePath());
                        pathValue = "images\\"+imgpath.getSubmittedFileName();
                        System.out.println("upload succes");
                }
                catch (Exception e) {
                        System.out.println(e);
                        }
                return pathValue;
    }
    public void clearAll() {
        this.idCategory = 0;
        this.category = null;
        this.picture = null;
    }


}


