package pojo;
// Generated 01-Oct-2018 22:10:55 by Hibernate Tools 4.3.1

import dao.AdminDAO;
import java.util.List;
import java.io.IOException;
import java.util.List;
import java.util.Map;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;
import javax.faces.context.FacesContext;

@ManagedBean
@SessionScoped
/**
 * TblAdmin generated by hbm2java
 */
public class TblAdmin implements java.io.Serializable {

    private Integer idAdmin;
    private String name;
    private String username;
    private String password;
    private List<TblAdmin> listAdmin;
    private int selectedAdmin;
    private String msg;

    public TblAdmin() {
    }

    public TblAdmin(String name, String username, String password) {
        this.name = name;
        this.username = username;
        this.password = password;
    }

    public Integer getIdAdmin() {
        return this.idAdmin;
    }

    public void setIdAdmin(Integer idAdmin) {
        this.idAdmin = idAdmin;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getUsername() {
        return this.username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public String getPassword() {
        return this.password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public List<TblAdmin> getListAdmin() {
        return listAdmin;
    }

    public void setListAdmin(List<TblAdmin> listAdmin) {
        this.listAdmin = listAdmin;
    }

    public int getSelectedAdmin() {
        return selectedAdmin;
    }

    public void setSelectedAdmin(int selectedAdmin) {
        
        this.selectedAdmin = selectedAdmin;
    }

    public String getMsg() {
        return msg;
    }

    public void setMsg(String msg) {
        this.msg = msg;
    }
    public String validateLogin(){
        AdminDAO adm = new AdminDAO();
        boolean validate = adm.validateLogin(this);
        if (validate==true){
            this.msg = null;
            clearAll();   
            System.out.println("berhasil");
            return "webadmin?faces-redirect=true";
        }else {
            this.msg = "Username or Password it wrong!!!";
            System.out.println("gagal");
            return "login";
        }
    }

    public void saveData() {
        AdminDAO tblAdmin = new AdminDAO();
        tblAdmin.addTblAdmin(this);
        this.msg = "Berhasil simpan data..";
        this.clearAll();
    }

    public void updateData() {
        AdminDAO tblAdmin = new AdminDAO();
        tblAdmin.updateTblAdmin(this);
        this.msg = "Berhasil update data..";
        this.clearAll();
    }

    public void deleteData() {
        AdminDAO tblAdmin = new AdminDAO();
        tblAdmin.destroyTblAdmin(this);
        this.msg = "Berhasil hapus data..";
        this.clearAll();
    }

    public List<TblAdmin> getAllRecords() {
        this.msg = null;
        AdminDAO tblAdmin = new AdminDAO();
        listAdmin = tblAdmin.retrieveTblAdmin();
        return listAdmin;
    }

    public List<TblAdmin> getAllTblAdminID() {
        AdminDAO tblAdmin = new AdminDAO();
        listAdmin = tblAdmin.retrieveTblAdminID();
        return listAdmin;
    }

    public void infoTblAdminByID() {
        AdminDAO tblAdmin = new AdminDAO();
        List<TblAdmin> ls = tblAdmin.getbyID(selectedAdmin);
        this.idAdmin = ls.get(0).idAdmin;
        this.name = ls.get(0).name;
        this.username = ls.get(0).username;
        this.password = ls.get(0).password;

    }

    public void clearAll() {
        this.idAdmin = 0;
        this.name = null;
        this.username = null;
        this.password = null;
        this.msg = null;
    }
    
}
