package pojo;
// Generated 01-Oct-2018 22:10:55 by Hibernate Tools 4.3.1

import dao.LyricDAO;
import java.util.List;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;




/**
 * TblLyric generated by hbm2java
 */
@ManagedBean
@SessionScoped
public class TblLyric  implements java.io.Serializable {


     private Integer idLyric;
     private String songTitle;
     private String singer;
     private String lyric;
     private String category;
     private List<TblLyric> listLyric;
     private int idCategory;
     private int selectedLyric;
     private String msg;
     private int id;
     

    public TblLyric() {
    }

    public TblLyric(String songTitle, String singer, String lyric, String category) {
       this.songTitle = songTitle;
       this.singer = singer;
       this.lyric = lyric;
       this.category = category;
    }
   
    public Integer getIdLyric() {
        return this.idLyric;
    }
    
    public void setIdLyric(Integer idLyric) {
        this.idLyric = idLyric;
    }
    public String getSongTitle() {
        return this.songTitle;
    }
    
    public void setSongTitle(String songTitle) {
        this.songTitle = songTitle;
    }
    public String getSinger() {
        return this.singer;
    }
    
    public void setSinger(String singer) {
        this.singer = singer;
    }
    public String getLyric() {
        return this.lyric;
    }
    
    public void setLyric(String lyric) {
        this.lyric = lyric;
    }
    public String getCategory() {
        return this.category;
    }
    
    public void setCategory(String category) {
        this.category = category;
    }

    public List<TblLyric> getListLyric() {
        return listLyric;
    }

    public void setListAdmin(List<TblLyric> listLyric) {
        this.listLyric = listLyric;
    }

    public int getSelectedLyric() {
        return selectedLyric;
    }

    public void setSelectedLyric(int selectedAdmin) {
        
        this.selectedLyric = selectedAdmin;
    }

    public String getMsg() {
        return msg;
    }

    public void setMsg(String msg) {
        this.msg = msg;
    }

    public int getIdCategory() {
        return idCategory;
    }

    public void setIdCategory(int idCategory) {
        this.idCategory = idCategory;
    }
    
    

    public void saveData() {
        LyricDAO tblLyric = new LyricDAO();
        setIdCategory(this.id);
        tblLyric.addTblLyric(this);
        this.msg = "Berhasil simpan data..";
        this.clearAll();
    }

    public void updateData() {
        LyricDAO tblLyric = new LyricDAO();
        tblLyric.updateTblLyric(this);
        this.msg = "Berhasil update data..";
        this.clearAll();
    }

    public void deleteData() {
        LyricDAO tblLyric = new LyricDAO();
        tblLyric.destroyTblLyric(this);
        this.msg = "Berhasil hapus data..";
        this.clearAll();
    }

    public List<TblLyric> getAllRecords() {
        this.msg = null;
        LyricDAO tblLyric = new LyricDAO();
        listLyric = tblLyric.retrieveTblLyric();
        return listLyric;
    }

    public List<TblLyric> getAllTblLyricID() {
        LyricDAO tblLyric = new LyricDAO();
        listLyric = tblLyric.retrieveTblLyricID();
        return listLyric;
    }

    public void infoTblLyricByID() {
        LyricDAO tblLyric = new LyricDAO();
        List<TblLyric> ls = tblLyric.getbyID(selectedLyric);
        this.idLyric = ls.get(0).idLyric;
        this.songTitle = ls.get(0).songTitle;
        this.singer = ls.get(0).singer;
        this.lyric = ls.get(0).lyric;
        this.category = ls.get(0).category;

    }
    
    public String linkLyrics(int id){
        clearAll();
        LyricDAO tblLyric = new LyricDAO();
        List<TblLyric> ls = tblLyric.ambildatalyricbyID(id);
        this.songTitle = ls.get(0).songTitle;
        this.singer = ls.get(0).singer;
        this.lyric = ls.get(0).lyric;
        return "lyric?faces-redirect=true";
    }
    
    public String linkSonglist(int id){
        this.idCategory = id;
        return "listsong?faces-redirect=true";
    }
    
    public List<TblLyric> ambilSonglistbyCat(int id) {
        LyricDAO tblLyric = new LyricDAO();
        listLyric = tblLyric.retrieveSongLyricsbyID(id);
        return listLyric;
    }
    
    
    
    public List<TblLyric> ambilDataLyrics() {
        LyricDAO tblLyric = new LyricDAO();
        listLyric = tblLyric.retrieveTblLyric();
        return listLyric;
    }
    
    public void ambilDataLyricsbyID(int id) {
        LyricDAO tblLyric = new LyricDAO();
        listLyric = tblLyric.retrieveTblLyric();
        
    }
    
    

    public void clearAll() {
        this.idLyric = 0;
        this.songTitle = null;
        this.singer = null;
        this.lyric = null;
        this.category = null;
    }

    /**
     * @return the id
     */
    public int getId() {
        return id;
    }

    /**
     * @param id the id to set
     */
    public void setId(int id) {
        this.id = id;
    }



}